services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: tfms-app
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:1.25-alpine
    container_name: tfms-nginx
    restart: unless-stopped
    ports:
      - "6060:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.1
    container_name: tfms-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app_tfms
      MYSQL_USER: app_tfms
      MYSQL_PASSWORD: "Tfm123!"
      MYSQL_ROOT_PASSWORD: "Tfm123!"
    ports:
      - "6606:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:20-alpine
    container_name: tfms-node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: ["npm"]

  adminer:
    image: adminer:4
    container_name: tfms-adminer
    restart: unless-stopped
    ports:
      - "6061:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql

volumes:
  mysql_data:
